//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAPI.Resources.Items {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPAPI.Resources.Items.ItemResource", typeof(ItemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanNotDeleteItem.
        /// </summary>
        internal static string CanNotDeleteItem {
            get {
                return ResourceManager.GetString("CanNotDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanNotDeleteItemGroup.
        /// </summary>
        internal static string CanNotDeleteItemGroup {
            get {
                return ResourceManager.GetString("CanNotDeleteItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanNotDeletePrice.
        /// </summary>
        internal static string CanNotDeletePrice {
            get {
                return ResourceManager.GetString("CanNotDeletePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanNotDeleteUnit.
        /// </summary>
        internal static string CanNotDeleteUnit {
            get {
                return ResourceManager.GetString("CanNotDeleteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group not found!.
        /// </summary>
        internal static string ItemGroupNotFound {
            get {
                return ResourceManager.GetString("ItemGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found!.
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentItemGroupNotFound.
        /// </summary>
        internal static string ParentItemGroupNotFound {
            get {
                return ResourceManager.GetString("ParentItemGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceNotFound.
        /// </summary>
        internal static string PriceNotFound {
            get {
                return ResourceManager.GetString("PriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisBarCodeExist.
        /// </summary>
        internal static string ThisBarCodeExist {
            get {
                return ResourceManager.GetString("ThisBarCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitNotFound.
        /// </summary>
        internal static string UnitNotFound {
            get {
                return ResourceManager.GetString("UnitNotFound", resourceCulture);
            }
        }
    }
}
